---
# tasks file for prereqs
- name: Install aptitude using apt
  apt:
    name: aptitude
    state: present
    update_cache: yes
    force_apt_get: yes
  become: true

- name: Install required system packages
  apt:
    name: "{{ prereqs_packages }}"
    state: present
    update_cache: true
    force: yes
  become: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true

- name: Update apt and install docker-ce
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
    force: yes
  become: true

- name: Add user vagrant to the docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: true
